services:
  fastapi_app:
    build: .
    image: nocodeml/backend:dev
    container_name: fastapi_app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - .:/app
      - dataset_files:/app/dataset_files
      - ./keys/fastapi-storage-key.json:/app/fastapi-storage-key.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/fastapi-storage-key.json 
  
  postgres:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"

  celery_worker_train:
    image: nocodeml/backend:dev
    container_name: celery_worker
    command: celery -A app.worker.celery_app worker --loglevel=info -Q train --concurrency=4
    volumes:
      - .:/app
      - ./keys/fastapi-storage-key.json:/app/fastapi-storage-key.json
    depends_on:
      - redis
      - fastapi_app
      - postgres
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/fastapi-storage-key.json

  celery_worker_plot:
    image: nocodeml/backend:dev
    container_name: celery_worker_plot
    command: celery -A app.worker.celery_app worker --loglevel=info -Q plot --concurrency=2
    volumes:
      - .:/app
      - ./keys/fastapi-storage-key.json:/app/fastapi-storage-key.json
    depends_on:
      - redis
      - fastapi_app
      - postgres
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/fastapi-storage-key.json

volumes:
  postgres_data:
  dataset_files:


